###################################
###################################
##
## BTAP ML - INPUT CONFIGURATION FILE
##
## Each value is used for the BTAP surrogate model program, but can also
## be provided through the designed CLI.
##
## NOTE: The docker image uses the root path '/home/btap_ml/'
##       The input data will be placed in the drive mounted to '/home/btap_ml/input/'
##       The output data will be placed in the drive mounted to '/home/btap_ml/output/'
##       Thus, all input paths specified in this file should be relative to the drive mounted
##       to '/home/btap_ml/input/'.
##       Example: If you mount 'C:/Users/username/Downloads/' to 'home/btap_ml/input' when running,
##       and you use the 'input_config.yml' file within 'C:/Users/username/Downloads/config/input_config.yml',
##       then the value which will be passed when calling the program will be:
##         python <filename>.py config/input_config.yml
##       This applies to any input path location specified in this file.
##
## NOTE: 
##       Presently, mixed datatypes are supported only when all data utilized has mixed datatypes in the same
##       columns.
##       
###################################

###################################
##
## USAGE NOTES (if needed for logging purposes)
## - ...
##
###################################

# Random seed
# Default value=7
random_seed: 7

# Selected model type
# 'rf' for Random Forest
# 'mlp' for Multi-Layer Perceptron
selected_model_type: "rf"

###################################
##
## FOR INPUT PREPROCESSING (ONLY USED FOR TRAINING)
##
###################################
# Specify the inputs for the building file(s) to be used for training
building_param_files: [
    # Electricity file (mandatory)
    "output_Elec.xlsx",
    # Gas file (optional, leave as an empty string if unused)
    "output_NG.xlsx",
  ]
# Specify the inputs for the energy file(s) to be used for training
energy_param_files: [
    # Electricity file (mandatory)
    "Ottawa_MidR_Elec_merged.csv",
    # Gas file (optional, leave as an empty string if unused)
    "Ottawa_MidR_NG_merged.csv",
  ]
# Specify the input for the building file to be used for train validation (optional)
# Default value=''
val_building_param_file: ""
# Specify the input for the energy file to be used for train validation (optional)
# Default value=''
val_energy_param_file: ""

###################################
##
## FOR FEATURE SELECTION (ONLY USED FOR TRAINING)
##
###################################
# Specify the estmator type to be used (lasso is the default if blank or unspecified)
# As of 04-27-2022, the options are:
#     linear
#     elasticnet (can take a very long time to complete)
#     xgb (can take a very long time to complete)
#     lasso (DEFAULT if empty)
# Default value=''
estimator_type: ""

###################################
##
## EACH VALUE BELOW IS USED FOR RUNNING A TRAINED MODEL
##
## NOTE: The weather key to be used is the value used by the :epw_file key.
##
###################################
# Folder path containing one or more .xlsx building paramter files
# All .xlsx files within the specified folder must be valid building files
# No final '/' is needed in the provided directory
batch_building_inputs: "Test"
# Start and end dates to be used when preprocessing data to receive energy predictions for
# Typically will remain as 1-1 to 12-31
# Expected format: Month_number-Day_number
simulation_start_date: "1-1"
simulation_end_date: "12-31"
###################################
## REQUIRED ENERGY FILES
###################################
# Filepath and filename of the trained ML model to be used (output from the training step)
energy_trained_model_file: "training_model_2025-01-13 11-38-44.201855\\rf\\energy\\model_training\\trained_model_rf.joblib"
# Filepath and filename of the ohe.pkl file generated from the preprocessing step when training a model
energy_ohe_file: "training_model_2025-01-13 11-38-44.201855\\rf\\energy\\ohe.pkl"
# Filepath and filename of the cleaned_columns.json file generated from the preprocessing step when training a model
energy_cleaned_columns_file: "training_model_2025-01-13 11-38-44.201855\\rf\\energy\\cleaned_columns.json"
# Filepath and filename of the scaler_X.pkl and scaler_y.pkl files to be used (located within the trained model output)
energy_scaler_X_file: "training_model_2025-01-13 11-38-44.201855\\rf\\energy\\model_training\\scaler_X.pkl"
energy_scaler_y_file: "training_model_2025-01-13 11-38-44.201855\\rf\\energy\\model_training\\scaler_y.pkl"
# Filepath and filename of the feature selection file to be used for training (located in training output)
energy_features_file: "training_model_2025-01-13 11-38-44.201855\\rf\\energy\\feature_selection\\feature_selection.json"
###################################
## REQUIRED COSTING FILES
###################################
# Filepath and filename of the trained ML model to be used (output from the training step)
costing_trained_model_file: "training_model_2025-01-13 11-38-44.201855\\rf\\costing\\model_training\\trained_model_rf.joblib"
# Filepath and filename of the ohe.pkl file generated from the preprocessing step when training a model
costing_ohe_file: "training_model_2025-01-13 11-38-44.201855\\rf\\costing\\ohe.pkl"
# Filepath and filename of the cleaned_columns.json file generated from the preprocessing step when training a model
costing_cleaned_columns_file: "training_model_2025-01-13 11-38-44.201855\\rf\\costing\\cleaned_columns.json"
# Filepath and filename of the scaler_X.pkl and scaler_y.pkl files to be used (located within the trained model output)
costing_scaler_X_file: "training_model_2025-01-13 11-38-44.201855\\rf\\costing\\model_training\\scaler_X.pkl"
costing_scaler_y_file: "training_model_2025-01-13 11-38-44.201855\\rf\\costing\\model_training\\scaler_y.pkl"
# Filepath and filename of the feature selection file to be used for training (located in training output)
costing_features_file: "training_model_2025-01-13 11-38-44.201855\\rf\\costing\\feature_selection\\feature_selection.json"
