apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: btap-pipeline-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.6, pipelines.kubeflow.org/pipeline_compilation_time: '2021-12-17T13:32:22.861945',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "MLP employed for Total
      energy consumed regression problem", "inputs": [{"default": "input_data/output_elec_2021-11-05.xlsx",
      "name": "build_params", "optional": true}, {"default": "input_data/total_hourly_res_elec_2021-11-05.csv",
      "name": "energy_hour", "optional": true}, {"default": "weather/CAN_QC_Montreal-Trudeau.Intl.AP.716270_CWEC2016.epw.parquet",
      "name": "weather", "optional": true}, {"default": "", "name": "build_params_val",
      "optional": true}, {"default": "", "name": "energy_hour_val", "optional": true},
      {"default": "output_data/preprocessing_out", "name": "output_path", "optional":
      true}, {"default": "output_data/feature_out", "name": "featureoutput_path",
      "optional": true}, {"default": "lasso", "name": "featureestimator", "optional":
      true}, {"default": "no", "name": "param_search", "optional": true}, {"default":
      "", "name": "build_params_gas", "optional": true}, {"default": "", "name": "energy_hour_gas",
      "optional": true}, {"default": "output_data/predict_out", "name": "predictoutput_path",
      "optional": true}], "name": "Btap Pipeline"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.6}
spec:
  entrypoint: btap-pipeline
  templates:
  - name: btap-pipeline
    inputs:
      parameters:
      - {name: build_params}
      - {name: build_params_gas}
      - {name: build_params_val}
      - {name: energy_hour}
      - {name: energy_hour_gas}
      - {name: energy_hour_val}
      - {name: featureestimator}
      - {name: featureoutput_path}
      - {name: output_path}
      - {name: param_search}
      - {name: predictoutput_path}
      - {name: weather}
    dag:
      tasks:
      - name: feature-selection-function
        template: feature-selection-function
        dependencies: [preprocess-data-function]
        arguments:
          parameters:
          - {name: featureestimator, value: '{{inputs.parameters.featureestimator}}'}
          - {name: featureoutput_path, value: '{{inputs.parameters.featureoutput_path}}'}
          - {name: output_path, value: '{{inputs.parameters.output_path}}'}
      - name: predict-function
        template: predict-function
        dependencies: [feature-selection-function]
        arguments:
          parameters:
          - {name: featureoutput_path, value: '{{inputs.parameters.featureoutput_path}}'}
          - {name: output_path, value: '{{inputs.parameters.output_path}}'}
          - {name: param_search, value: '{{inputs.parameters.param_search}}'}
          - {name: predictoutput_path, value: '{{inputs.parameters.predictoutput_path}}'}
      - name: preprocess-data-function
        template: preprocess-data-function
        arguments:
          parameters:
          - {name: build_params, value: '{{inputs.parameters.build_params}}'}
          - {name: build_params_gas, value: '{{inputs.parameters.build_params_gas}}'}
          - {name: build_params_val, value: '{{inputs.parameters.build_params_val}}'}
          - {name: energy_hour, value: '{{inputs.parameters.energy_hour}}'}
          - {name: energy_hour_gas, value: '{{inputs.parameters.energy_hour_gas}}'}
          - {name: energy_hour_val, value: '{{inputs.parameters.energy_hour_val}}'}
          - {name: output_path, value: '{{inputs.parameters.output_path}}'}
          - {name: weather, value: '{{inputs.parameters.weather}}'}
  - name: feature-selection-function
    container:
      args: []
      command: [python3, /pipelines/feature_selection.py, --in_obj_name, '{{inputs.parameters.output_path}}',
        --estimator_type, '{{inputs.parameters.featureestimator}}', --output_path,
        '{{inputs.parameters.featureoutput_path}}']
      image: k8scc01covidacr.azurecr.io/btap:22b925247f1fd668edefc8bf21143a3082864d26
      resources:
        limits: {memory: 32Gi}
        requests: {memory: 16Gi}
    inputs:
      parameters:
      - {name: featureestimator}
      - {name: featureoutput_path}
      - {name: output_path}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.6
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
      annotations: {pipelines.kubeflow.org/component_spec: '{"description": "Selects
          the feature that would be used in building the model", "implementation":
          {"container": {"command": ["python3", "/pipelines/feature_selection.py",
          "--in_obj_name", {"inputValue": "in_obj_name"}, "--estimator_type", {"inputValue":
          "estimator_type"}, "--output_path", {"inputValue": "output_path"}], "image":
          "k8scc01covidacr.azurecr.io/btap:22b925247f1fd668edefc8bf21143a3082864d26"}},
          "inputs": [{"description": "Name of minio bucket to access data from", "name":
          "in_obj_name", "type": "String"}, {"description": "Name of minio bucket
          to access data from", "name": "estimator_type", "type": "String"}, {"description":
          "Path where the output data will be stored.", "name": "output_path", "type":
          "String"}], "name": "Feature selection Function"}', pipelines.kubeflow.org/component_ref: '{"digest":
          "c0da383067a07bb9c59193118cbf27c59f79c2d0909cf95d39e84e3a4a9d4d1a", "url":
          "yaml/feature_selection.yml"}', pipelines.kubeflow.org/arguments.parameters: '{"estimator_type":
          "{{inputs.parameters.featureestimator}}", "in_obj_name": "{{inputs.parameters.output_path}}",
          "output_path": "{{inputs.parameters.featureoutput_path}}"}'}
  - name: predict-function
    container:
      args: []
      command: [python3, /pipelines/predict.py, --param_search, '{{inputs.parameters.param_search}}',
        --in_obj_name, '{{inputs.parameters.output_path}}', --features, '{{inputs.parameters.featureoutput_path}}',
        --output_path, '{{inputs.parameters.predictoutput_path}}']
      image: k8scc01covidacr.azurecr.io/btap:22b925247f1fd668edefc8bf21143a3082864d26
      resources:
        limits: {memory: 32Gi}
        requests: {memory: 16Gi}
    inputs:
      parameters:
      - {name: featureoutput_path}
      - {name: output_path}
      - {name: param_search}
      - {name: predictoutput_path}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.6
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
      annotations: {pipelines.kubeflow.org/component_spec: '{"description": "Predicts
          the output variable", "implementation": {"container": {"command": ["python3",
          "/pipelines/predict.py", "--param_search", {"inputValue": "param_search"},
          "--in_obj_name", {"inputValue": "in_obj_name"}, "--features", {"inputValue":
          "features"}, "--output_path", {"inputValue": "output_path"}], "image": "k8scc01covidacr.azurecr.io/btap:22b925247f1fd668edefc8bf21143a3082864d26"}},
          "inputs": [{"description": "Specify whether to search for hyperparameter,
          yes or no", "name": "param_search", "type": "String"}, {"description": "Name
          of the input path for process data", "name": "in_obj_name", "type": "String"},
          {"description": "Name of the input path for selected features data", "name":
          "features", "type": "String"}, {"description": "Name of the input path for
          selected features data", "name": "output_path", "type": "String"}], "name":
          "Predict Function"}', pipelines.kubeflow.org/component_ref: '{"digest":
          "c84285a39dedbc7e42e7c6f7394918e13fa3ac18b55a484e2be8d4d239e0238a", "url":
          "yaml/predict.yml"}', pipelines.kubeflow.org/arguments.parameters: '{"features":
          "{{inputs.parameters.featureoutput_path}}", "in_obj_name": "{{inputs.parameters.output_path}}",
          "output_path": "{{inputs.parameters.predictoutput_path}}", "param_search":
          "{{inputs.parameters.param_search}}"}'}
  - name: preprocess-data-function
    container:
      args: []
      command: [python3, /pipelines/preprocessing.py, --in_hour, '{{inputs.parameters.energy_hour}}',
        --in_build_params, '{{inputs.parameters.build_params}}', --in_weather, '{{inputs.parameters.weather}}',
        --in_hour_val, '{{inputs.parameters.energy_hour_val}}', --in_build_params_val,
        '{{inputs.parameters.build_params_val}}', --in_hour_gas, '{{inputs.parameters.energy_hour_gas}}',
        --in_build_params_gas, '{{inputs.parameters.build_params_gas}}', --output_path,
        '{{inputs.parameters.output_path}}']
      image: k8scc01covidacr.azurecr.io/btap:22b925247f1fd668edefc8bf21143a3082864d26
      resources:
        limits: {memory: 32Gi}
        requests: {memory: 16Gi}
    inputs:
      parameters:
      - {name: build_params}
      - {name: build_params_gas}
      - {name: build_params_val}
      - {name: energy_hour}
      - {name: energy_hour_gas}
      - {name: energy_hour_val}
      - {name: output_path}
      - {name: weather}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.6
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
      annotations: {pipelines.kubeflow.org/component_spec: '{"description": "Clean
          and split the data downloaded from minio which is the output from download_data.yaml",
          "implementation": {"container": {"command": ["python3", "/pipelines/preprocessing.py",
          "--in_hour", {"inputValue": "in_hour"}, "--in_build_params", {"inputValue":
          "in_build_params"}, "--in_weather", {"inputValue": "in_weather"}, "--in_hour_val",
          {"inputValue": "in_hour_val"}, "--in_build_params_val", {"inputValue": "in_build_params_val"},
          "--in_hour_gas", {"inputValue": "in_hour_gas"}, "--in_build_params_gas",
          {"inputValue": "in_build_params_gas"}, "--output_path", {"inputValue": "output_path"}],
          "image": "k8scc01covidacr.azurecr.io/btap:22b925247f1fd668edefc8bf21143a3082864d26"}},
          "inputs": [{"description": "The minio location and filename for the hourly
          energy consumption file is located. This would be the path for the electric
          hourly file if it exist.", "name": "in_hour", "type": "String"}, {"description":
          "The minio location and filename the building simulation I/O file. This
          would be the path for the electric hourly file if it exist.", "name": "in_build_params",
          "type": "String"}, {"description": "The minio location and filename for
          the converted  weather file to be read", "name": "in_weather", "type": "String"},
          {"description": "The minio location and filename for the hourly energy consumption
          file for the validation set, if it exist.", "name": "in_hour_val", "type":
          "String"}, {"description": "The minio location and filename for the building
          simulation I/O file for the validation set, if it exist.", "name": "in_build_params_val",
          "type": "String"}, {"description": "The minio location and filename for
          the hourly energy consumption file is located. This would be the path for
          the gas hourly file if it exist.", "name": "in_hour_gas", "type": "String"},
          {"description": "The minio location and filename the building simulation
          I/O file. This would be the path for the gas hourly file if it exist.",
          "name": "in_build_params_gas", "type": "String"}, {"description": "The minio
          location and filename where the output file should be written.", "name":
          "output_path", "type": "String"}], "name": "Preprocess data function"}',
        pipelines.kubeflow.org/component_ref: '{"digest": "65d9391c0ad166ea670aefb2eaf9a0fdc0b031e4edee5f17cae21c40c97ffcd8",
          "url": "yaml/preprocessing.yml"}', pipelines.kubeflow.org/arguments.parameters: '{"in_build_params":
          "{{inputs.parameters.build_params}}", "in_build_params_gas": "{{inputs.parameters.build_params_gas}}",
          "in_build_params_val": "{{inputs.parameters.build_params_val}}", "in_hour":
          "{{inputs.parameters.energy_hour}}", "in_hour_gas": "{{inputs.parameters.energy_hour_gas}}",
          "in_hour_val": "{{inputs.parameters.energy_hour_val}}", "in_weather": "{{inputs.parameters.weather}}",
          "output_path": "{{inputs.parameters.output_path}}"}'}
  arguments:
    parameters:
    - {name: build_params, value: input_data/output_elec_2021-11-05.xlsx}
    - {name: energy_hour, value: input_data/total_hourly_res_elec_2021-11-05.csv}
    - {name: weather, value: weather/CAN_QC_Montreal-Trudeau.Intl.AP.716270_CWEC2016.epw.parquet}
    - {name: build_params_val, value: ''}
    - {name: energy_hour_val, value: ''}
    - {name: output_path, value: output_data/preprocessing_out}
    - {name: featureoutput_path, value: output_data/feature_out}
    - {name: featureestimator, value: lasso}
    - name: param_search
      value: "no"
    - {name: build_params_gas, value: ''}
    - {name: energy_hour_gas, value: ''}
    - {name: predictoutput_path, value: output_data/predict_out}
  serviceAccountName: pipeline-runner
