###################################
##
## BTAP ML - INPUT CONFIGURATION FILE
##
## Each value is used for the BTAP surrogate model program, but can also
## be provided through the designed CLI.
##
## NOTE: The docker image uses the root path '/home/btap_ml/'
##       The input data will be placed in the drive mounted to '/home/btap_ml/input/'
##       The output data will be placed in the drive mounted to '/home/btap_ml/output/'
##       Thus, all input paths specified in this file should be relative to the drive mounted
##       to '/home/btap_ml/input/'.
##       Example: If you mount 'C:/Users/username/Downloads/' to 'home/btap_ml/input' when running,
##       and you use the 'input_config.yml' file within 'C:/Users/username/Downloads/config/input_config.yml',
##       then the value which will be passed when calling the program will be:
##         python <filename>.py config/input_config.yml
##       This applies to any input path location specified in this file.
##
###################################

# Random seed
:random_seed: 7

###################################
##
## FOR WEATHER PROCESSING (USED FOR BOTH TRAINING AND RUNNING A MODEL)
##
###################################
# Specify the epw key to be used
:epw_file: [
  'CAN_QC_Montreal-Trudeau.Intl.AP.716270_CWEC2016.epw',
# 'CAN_NS_Halifax.Dockyard.713280_CWEC2016.epw',
# 'CAN_AB_Edmonton.Intl.AP.711230_CWEC2016.epw',
# 'CAN_BC_Vancouver.Intl.AP.718920_CWEC2016.epw',
# 'CAN_AB_Calgary.Intl.AP.718770_CWEC2016.epw',
# 'CAN_ON_Toronto.Pearson.Intl.AP.716240_CWEC2016.epw',
# 'CAN_YT_Whitehorse.Intl.AP.719640_CWEC2016.epw'
]

###################################
##
## FOR INPUT PREPROCESSING (ONLY USED FOR TRAINING)
##
###################################
# Specify the inputs for the building file(s) to be used for training
:building_param_files: [
  # Electricity file (mandatory)
  '',
  # Gas file (optional, leave as an empty string if unused)
  ''
]
# Specify the inputs for the energy file(s) to be used for training
:energy_param_files: [
  # Electricity file (mandatory)
  '',
  # Gas file (optional, leave as an empty string if unused)
  ''
]
# Specify the input for the building file to be used for train validation (optional)
:val_building_param_files: ''
# Specify the input for the energy file to be used for train validation (optional)
:val_energy_param_files: ''

###################################
##
## FOR FEATURE SELECTION (ONLY USED FOR TRAINING)
##
###################################
# Specify the estmator type to be used (lasso is the default if blank or unspecified)
# As of 04-27-2022, the options are:
#     linear
#     elasticnet (can take a very long time to complete)
#     xgb (can take a very long time to complete)
#     lasso (DEFAULT if empty)
:estimator_type: ''

###################################
##
## FOR MODEL TRAINING AFTER PREPROCESSING (ONLY USED FOR TRAINING)
##
###################################
# Determine whether the training should perform a hyperparameter search
# Selecting yes will increase the training time
# Either 'yes' or 'no'
:param_search: 'no'

###################################
##
## EACH VALUE BELOW IS USED FOR RUNNING A TRAINED MODEL
##
## NOTE: The weather key to be used is the value used by the :epw_file key.
##
###################################
# Filepath and filename of the trained ML model to be used (output from the training step)
:trained_model_file: ''
# Filepath and filename of the ohe.pkl file generated from the preprocessing step when training a model
:ohe_file: ''
# Filepath and filename of the cleaned_columns.json file generated from the preprocessing step when training a model
:cleaned_columns_file: ''
# Filepath and filename of the scaler_X.pkl and scaler_y.pkl files to be used (located within the trained model output)
:scaler_X_file: ''
:scaler_y_file: ''
# Filepath and filename of the feature selection file to be used for training (located in training output)
:features_file: ''
# Folder path containing one or more .xlsx building paramter files
# All .xlsx files within the specified folder must be valid building files
# No final '/' is needed in the provided directory
:batch_building_inputs: ''
# Start and end dates to be used when preprocessing data to receive predictions for
# Typically will remain as 1-1 to 12-31
# Expected format: Month_number-Day_number
:simulation_start_date: '1-1'
:simulation_end_date: '12-31'
