name: Documentation CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, which is where the next step will look for it.
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      # Make graphviz available
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1

      # Build the documentation as HTML.
      - name: Build and Commit
        uses: sphinx-notes/pages@1.0
        with:
          documentation_path: "docs/"

      # Publish built docs to gh-pages branch.
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
